language: python
python:
    - "2.7"

install:
    - "python setup.py install"
    - "curl http://www.cups.org/software/ipptool/ipptool-20130731-linux-ubuntu-x86_64.tar.gz | tar xvzf -"
    - "echo \"[main]\nipptool_path = \"$TRAVIS_BUILD_DIR\"/ipptool-20130731/ipptool\" > ~/.pyipptool.cfg"

script: "python setup.py test"

notifications:
    email: false
